version: '3'
services:
  mq:
    image: microservices:rmq
    ports:
       ["15673:15672","5673:5672"]
    expose:
      - "5672"
      - "15672"
  db:
    image: microservices:psql
    ports:
      - "5433:5432"
    expose:
      - "5432"
  ms_rest_api:
    image: microservices:ms_rest_api
    depends_on: 
      - mq
    links: 
      - db
      - mq
    expose:
      - "8081"
      - "8082"
    ports:
       ["8080:8081","8085:8082"]
  ms_presistence:
    image: microservices:ms_presistence
    depends_on: 
      - mq
    links: 
      - db
      - mq
  ms_generation:
    image: microservices:ms_generation
    depends_on: 
      - mq
    links:
      - mq
    
