bind_addr = "0.0.0.0:8082"
bind_web_addr = "0.0.0.0:8081"
log_level = "debug"
database_url = "host=db user=remote password=Cfyz11005310 dbname=microservices sslmode=disable"
rmq_url = "amqp://remote:Cfyz11005310@mq"
rmq_queue = "delay"