bind_addr = ":8082"
log_level = "debug"
database_url = "host=localhost user=remote password=Cfyz11005310 dbname=microservices sslmode=disable"
rmq_url = "amqp://remote:Cfyz11005310@localhost:5672"
rmq_queue = "delay"