// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgRequest struct {
	JsonUser             string   `protobuf:"bytes,1,opt,name=jsonUser,proto3" json:"jsonUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRequest) Reset()         { *m = MsgRequest{} }
func (m *MsgRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRequest) ProtoMessage()    {}
func (*MsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *MsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRequest.Unmarshal(m, b)
}
func (m *MsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRequest.Marshal(b, m, deterministic)
}
func (m *MsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequest.Merge(m, src)
}
func (m *MsgRequest) XXX_Size() int {
	return xxx_messageInfo_MsgRequest.Size(m)
}
func (m *MsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequest proto.InternalMessageInfo

func (m *MsgRequest) GetJsonUser() string {
	if m != nil {
		return m.JsonUser
	}
	return ""
}

type MsgReply struct {
	Sent                 bool     `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgReply) Reset()         { *m = MsgReply{} }
func (m *MsgReply) String() string { return proto.CompactTextString(m) }
func (*MsgReply) ProtoMessage()    {}
func (*MsgReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *MsgReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgReply.Unmarshal(m, b)
}
func (m *MsgReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgReply.Marshal(b, m, deterministic)
}
func (m *MsgReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgReply.Merge(m, src)
}
func (m *MsgReply) XXX_Size() int {
	return xxx_messageInfo_MsgReply.Size(m)
}
func (m *MsgReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgReply.DiscardUnknown(m)
}

var xxx_messageInfo_MsgReply proto.InternalMessageInfo

func (m *MsgReply) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

func init() {
	proto.RegisterType((*MsgRequest)(nil), "MsgRequest")
	proto.RegisterType((*MsgReply)(nil), "MsgReply")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe0, 0xe2, 0xf2, 0x2d, 0x4e, 0x0f, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0xc8, 0x2a, 0xce, 0xcf, 0x0b, 0x2d, 0x4e, 0x2d,
	0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x95, 0xe4, 0xb8, 0x38, 0xc0, 0x2a, 0x0b,
	0x72, 0x2a, 0x85, 0x84, 0xb8, 0x58, 0x8a, 0x53, 0xf3, 0x4a, 0xc0, 0x6a, 0x38, 0x82, 0xc0, 0x6c,
	0xa3, 0x18, 0x2e, 0x2e, 0x90, 0xba, 0xe0, 0xd4, 0xbc, 0x94, 0xd4, 0x22, 0x21, 0x15, 0x2e, 0x0e,
	0x10, 0x2b, 0x20, 0xb1, 0xb8, 0x58, 0x88, 0x5b, 0x0f, 0x61, 0x85, 0x14, 0xa7, 0x1e, 0xcc, 0x14,
	0x25, 0x06, 0x21, 0x0d, 0x2e, 0x9e, 0xa0, 0xd4, 0x92, 0xa2, 0xcc, 0xd4, 0xb2, 0x54, 0xfc, 0x2a,
	0x93, 0xd8, 0xc0, 0xce, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x29, 0x83, 0x57, 0x82, 0xbc,
	0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserSenderClient is the client API for UserSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserSenderClient interface {
	SendPass(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgReply, error)
	RetrievePass(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgReply, error)
}

type userSenderClient struct {
	cc *grpc.ClientConn
}

func NewUserSenderClient(cc *grpc.ClientConn) UserSenderClient {
	return &userSenderClient{cc}
}

func (c *userSenderClient) SendPass(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgReply, error) {
	out := new(MsgReply)
	err := c.cc.Invoke(ctx, "/UserSender/SendPass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSenderClient) RetrievePass(ctx context.Context, in *MsgRequest, opts ...grpc.CallOption) (*MsgReply, error) {
	out := new(MsgReply)
	err := c.cc.Invoke(ctx, "/UserSender/RetrievePass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSenderServer is the server API for UserSender service.
type UserSenderServer interface {
	SendPass(context.Context, *MsgRequest) (*MsgReply, error)
	RetrievePass(context.Context, *MsgRequest) (*MsgReply, error)
}

// UnimplementedUserSenderServer can be embedded to have forward compatible implementations.
type UnimplementedUserSenderServer struct {
}

func (*UnimplementedUserSenderServer) SendPass(ctx context.Context, req *MsgRequest) (*MsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPass not implemented")
}
func (*UnimplementedUserSenderServer) RetrievePass(ctx context.Context, req *MsgRequest) (*MsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrievePass not implemented")
}

func RegisterUserSenderServer(s *grpc.Server, srv UserSenderServer) {
	s.RegisterService(&_UserSender_serviceDesc, srv)
}

func _UserSender_SendPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSenderServer).SendPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserSender/SendPass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSenderServer).SendPass(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserSender_RetrievePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSenderServer).RetrievePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserSender/RetrievePass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSenderServer).RetrievePass(ctx, req.(*MsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserSender_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserSender",
	HandlerType: (*UserSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPass",
			Handler:    _UserSender_SendPass_Handler,
		},
		{
			MethodName: "RetrievePass",
			Handler:    _UserSender_RetrievePass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
